name: flutter_review_app
description: A Flutter review app with auth and feed features
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  carousel_slider: ^5.0.0

  js: ^0.7.1

  # Media & Upload
  cloudinary_public: ^0.23.1
  image_picker: ^1.0.4
  file_picker: ^10.2.0
  video_player: ^2.8.1

  # UI & UX
  flutter_rating_bar: ^4.0.1
  dropdown_search: ^5.0.6
  intl: ^0.20.2
  share_plus: ^11.0.0

  # State Management
  flutter_riverpod: ^2.4.9

  # Utils
  uuid: ^4.2.1
  cached_network_image: ^3.3.0

  cupertino_icons: ^1.0.2

  month_year_picker: ^0.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true