// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeNYi6aGkZd4erTbZIxJLvlKBvsdhLqxQ',
    appId: '1:135059362859:web:fb92c504128dd06c76466e',
    messagingSenderId: '135059362859',
    projectId: 'airline-reviews-8816c',
    authDomain: 'airline-reviews-8816c.firebaseapp.com',
    storageBucket: 'airline-reviews-8816c.firebasestorage.app',
    measurementId: 'G-NCPQZWJHJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSjNZLw6wUO1oYgDeVwIMOkVqY_LF2X8I',
    appId: '1:135059362859:android:69f1131f0d38d31176466e',
    messagingSenderId: '135059362859',
    projectId: 'airline-reviews-8816c',
    storageBucket: 'airline-reviews-8816c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk9iTWnbp3Cb81uScevs2hq7RxaH0Kvf4',
    appId: '1:135059362859:ios:eb6d7df49500684676466e',
    messagingSenderId: '135059362859',
    projectId: 'airline-reviews-8816c',
    storageBucket: 'airline-reviews-8816c.firebasestorage.app',
    iosBundleId: 'com.example.airlinereviews',
  );
}
